apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    purpose: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
  labels:
    purpose: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    purpose: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  labels:
    purpose: platform