apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform

  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.16.0
      helm:
        valueFiles:
          - $values/platform/aws-load-balancer-controller/values.yaml
    - repoURL: https://github.com/my-git/k8s.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: aws-load-balancer-tls
      namespace: kube-system
      jsonPointers:
        - /data

    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'

    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'