apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.14.1
      helm:
        valueFiles:
          - $values/platform/external-secrets/values.yaml
    - repoURL: https://github.com/my-git/k8s.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/my-git/k8s.git
      targetRevision: main
      path: platform/external-secrets/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true