apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-priorityclasses
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  source:
    repoURL: https://github.com/my-git/k8s.git
    targetRevision: main
    path: platform/priorityclasses
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true